#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# What kind of thing is this ("lesson")? #Don't change
kind: "lesson"

type: "episode" # The other valid option is "episode_r"

# Overall title for pages.
title: "Lesson Title"
form_title: "Lesson+Title" # This is required for the surveys

# Email address, no mailto:
email: "rsginfo@soton.ac.uk"

# Specify the location of the workshop
venue: "TBC"           # name of location use "online" if online
address: "TBC"         # address of location or url of platform
platform-name: "TBC"   # name of online platform e.g. Teams, Zoom e.t.c
country: "TBC"         # e.g. gb
language: "TBC"        # e.g. en
latitude: "50.909698"    # latitude of location (Soton: 50.909698)
longitude: "-1.404351"   # longitude of location (Soton: -1.404351)

# Specify the start and end date of the lesson
humandate: "TBC"      # e.g. "6th August"
humantime: "TBC"      # e.g. "09:00-17:00"
startdate: "TBC"        # e.g. YYYY-MM-DD # e.g. YYYY-MM-DD # This is required for the surveys NOTE: 1990-1-1 will not work
enddate: "TBC"          # e.g. YYYY-MM-DD

# Start time in minutes (0 to be clock-independent, 3:30 pm or 15:30 both okay).
start-time: 0

###
# It is unlikely you need to modify the values below this line. Unless you are developing content.
###
# Which carpentry is this ("rsg")?
# rsg: Southampton Research Software Group
carpentry: "rsg"

# Life cycle stage of the lesson
# See this page for more details: https://cdh.carpentries.org/the-lesson-life-cycle.html
# Possible values: "pre-alpha", "alpha", "beta", "stable"
life_cycle: "stable"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
repository: <USERNAME>/<PROJECT>

# Sites.
amy_site: "https://amy.carpentries.org/"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "https://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
lc_site: "https://librarycarpentry.org/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
rsg_site: "https://rsgsoton.net/"
template_repo: "https://github.com/carpentries/styles"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"
cc_by_human: "https://creativecommons.org/licenses/by/4.0/"

# order is critical
setup_docs:
  - text_editor.md

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:slug

include:
  - _includes/rsg/
  - _includes/
# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
  - .vendor/
  - vendor/
  - .docker-vendor/
  - submodules/


# Turn on built-in syntax highlighting.
highlighter: rouge

# Using the new jekyll remote themes
remote_theme: Southampton-RSG-Training/rsg-theme

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-target-blank
