name: Weekly Styles Update
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person who triggered the workflow'
        required: true
        default: 'scheduled run'
  schedule:
    # Run every Wednesday
    - cron: '0 0 * * 3'

jobs:
  check-token:
    name: "Check STYLES_WORKFLOW token"
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'carpentries/lesson-example' }}
    outputs:
      wf: ${{ steps.validate.outputs.wf }}
      repo: ${{ steps.validate.outputs.repo }}
    steps:
      - name: "validate token"
        id: validate
        uses: carpentries/actions/check-valid-credentials@main
        with:
          token: ${{ secrets.STYLES_WORKFLOW }}

  bad-token:
    name: "Invalid/Missing Token"
    runs-on: ubuntu-latest
    needs: check-token
    if: ${{ needs.check-token.outputs.wf != 'true' && github.repository == 'carpentries/lesson-example' }}
    steps:
      - name: "Instructions to create a new token"
        run: |
          printf "::warning::The STYLES_WORKFLOW secret is missing, invalid, "\
          "or does not have the right scope to update workflows.\n"\
          "If you want to have automated pull request updates to your workflows, "\
          "you will need to generate a new token by visiting "\
          "https://github.com/settings/tokens/new?scopes=repo,workflow&description=Styles%%20Token\n"\
          "Once you have created the token, go to "\
          "https://github.com/${{ github.repository }}/settings/secrets/actions/STYLES_WORKFLOW "\
          "to update it."

  update-styles:
    runs-on: ubuntu-latest
    name: Styles Update
    needs: check-token
    if: ${{ needs.check-token.outputs.wf == 'true' && github.repository == 'carpentries/lesson-example' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Record Date
        id: today
        run: |
          echo "::set-output name=date::$(date -I)"
          echo "::set-output name=min::$(date +%Y-%m-%d-%H-%M)"

      - name: Sync lesson with carpentries/styles
        id: update
        uses: carpentries/actions/update-styles@main
        env:
          LESSON: "Lesson Example"
          REF: ${{ github.ref }}
        with:
          commit: true

      - name: Create Pull Request
        id: cpr
        if: ${{ steps.update.outputs.update == 'true' }}
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.STYLES_WORKFLOW}}
          commit-message: "[actions] Sync lesson with carpentries/styles"
          branch: "update-styles-${{ steps.today.outputs.min }}"
          delete-branch: true
          title: "Update Styles (${{ steps.today.outputs.date }} via ${{ github.event.inputs.name }})"
          body: |
            Update styles repository. Please inspect the changes to make sure there are no conflicts with your lesson.

            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: "type:template and tools"
          # NOTE: This tag is repository-specific
          team-reviewers: core-team-curriculum
          draft: false

