name: Website
on:
  push:
    branches:
      - "main"
  pull_request: null
jobs:
  build-setup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the lesson
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python modules
        run: |
          python3 -m pip install --upgrade pip setuptools wheel pyyaml==5.3.1 requests
          python3 -m pip install -r requirements.txt

      - name: Run get setup
        run: |
          python bin/get_setup.py
          git add setup.md
          git commit -m 'adding generated setup'

      - name: Deploy the website to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: "."
          token: ${{ secrets.GITHUB_TOKEN }}
